#!/bin/bash
# =============================================================
# NDK clang-17 wrapper — installed by CI "Patch NDK clang-17" step.
# DO NOT EDIT THIS FILE without bumping the cache key in main.yml.
# =============================================================
#
# PURPOSE
# -------
# Intercepts EVERY compilation and link step that goes through the NDK
# toolchain. All arch-prefixed wrappers in the NDK bin directory
# (aarch64-linux-android21-clang, aarch64-linux-android21-clang++, etc.)
# are shell scripts that ultimately exec this single binary, so one
# wrapper here covers Kivy, HarfBuzz, SDL2_ttf (ndk-build), FreeType,
# and every other recipe compiled by python-for-android.
#
# The host compiler (GCC/x86_64 used to build hostpython3) is in a
# completely separate location and does NOT go through this wrapper.
#
# FLAGS ADDED
# -----------
# -Wno-cast-function-type-strict
# -Wno-cast-function-type
#     Clang 17 (NDK r26b) treats casts between incompatible function-pointer
#     types as fatal errors (-Wcast-function-type-strict). HarfBuzz uses
#     this pattern with FreeType Generic API; Kivy Cython extensions also
#     trigger it. These two flags suppress the diagnostic in C and C++ modes.
#
# -Wno-error=cast-function-type-strict
#     Belt-and-suspenders: removes the -Werror upgrade for this specific
#     warning even if something in the build chain sets -Werror globally.
#
# -Wno-unused-command-line-argument
#     Suppresses the "argument unused during compilation" warning that
#     -Wl,-z,max-page-size=16384 would produce in compile-only (-c) mode.
#     Without this, -Werror (if set) would turn that warning into an error.
#
# -Wl,-z,max-page-size=16384
#     Sets the ELF LOAD segment alignment to 16 KB, required for Android 15+
#     (API 35) compatibility. During compilation-only steps, Clang accepts
#     this flag and silently discards it (suppressed by the flag above).
#     During link steps, it is forwarded to lld and takes effect.

exec "$(dirname "$0")/clang-17.real" "$@" \
    -Wno-cast-function-type-strict \
    -Wno-cast-function-type \
    -Wno-error=cast-function-type-strict \
    -Wno-unused-command-line-argument \
    -Wl,-z,max-page-size=16384
